include:
  - https://cnb.cool/ilay1678/templates/-/blob/main/docker.cnb.yml
  - https://cnb.cool/ilay1678/templates/-/blob/main/docker.ghcr.yml
  - https://cnb.cool/ilay1678/templates/-/blob/main/sync_to_github.yml