name = "i-tools"
main = "src/worker.mjs"
compatibility_date = "2024-12-13"
compatibility_flags = [ "nodejs_compat" ]
pages_build_output_dir = ".vercel/output/static"
pages_build_command = "npx @cloudflare/next-on-pages@1"