#:schema node_modules/wrangler/config-schema.json
name = "alipan-tv-nuxt"
compatibility_date = "2024-11-06"
main = "./dist/worker/index.js"
pages_build_output_dir = "./dist"
assets = { directory = "./dist/public", binding = "ASSETS" }
# Workers Logs
# Docs: https://developers.cloudflare.com/workers/observability/logs/workers-logs/
# Configuration: https://developers.cloudflare.com/workers/observability/logs/workers-logs/#enable-workers-logs
[observability]
enabled = true
